/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lwm_ccalljava_JNITest */

#ifndef _Included_com_lwm_ccalljava_JNITest
#define _Included_com_lwm_ccalljava_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lwm_ccalljava_JNITest
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lwm_ccalljava_JNITest_callbackAdd
        (JNIEnv *, jobject);

/*
 * Class:     com_lwm_ccalljava_JNITest
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lwm_ccalljava_JNITest_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_lwm_ccalljava_JNITest
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lwm_ccalljava_JNITest_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_lwm_ccalljava_JNITest
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lwm_ccalljava_JNITest_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
